/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Voting__factory } from "./Voting__factory";
export { YourContract__factory } from "./YourContract__factory";
